<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

use Carbon\Carbon;

class SoapResource extends JsonResource
{
    public static $wrap = 'soap';

    public function toArray($request): array
    {
        return [
            'id' => $this->id,
            'clinical_note_id' => $this->clinical_note_id,
            'hpi' => $this->hpi,
            'family_hx' => $this->family_hx,
            'past_medical_hx' => $this->past_medical_hx,
            'social_hx' => $this->social_hx,
            'general' => $this->general,
            'general_dd' => $this->general_dd,
            'general_comments' => $this->general_comments,
            'skin' => $this->skin,
            'skin_dd' => $this->skin_dd,
            'skin_comments' => $this->skin_comments,
            'heent' => $this->heent,
            'heent_dd' => $this->heent_dd,
            'heent_comments' => $this->heent_comments,
            'neck' => $this->neck,
            'neck_dd' => $this->neck_dd,
            'neck_comments' => $this->neck_comments,
            'cardio' => $this->cardio,
            'cardio_dd' => $this->cardio_dd,
            'cardio_comments' => $this->cardio_comments,
            'respiratory' => $this->respiratory,
            'respiratory_dd' => $this->respiratory_dd,
            'respiratory_comments' => $this->respiratory_comments,
            'gi' => $this->gi,
            'gi_dd' => $this->gi_dd,
            'gi_comments' => $this->gi_comments,
            'urinary' => $this->urinary,
            'urinary_dd' => $this->urinary_dd,
            'urinary_comments' => $this->urinary_comments,
            'periph_vasc' => $this->periph_vasc,
            'periph_vasc_dd' => $this->periph_vasc_dd,
            'periph_vasc_comments' => $this->periph_vasc_comments,
            'msk' => $this->msk,
            'msk_dd' => $this->msk_dd,
            'msk_comments' => $this->msk_comments,
            'neuro' => $this->neuro,
            'neuro_dd' => $this->neuro_dd,
            'neuro_comments' => $this->neuro_comments,
            'endo' => $this->endo,
            'endo_dd' => $this->endo_dd,
            'endo_comments' => $this->endo_comments,
            'psychiatric' => $this->psychiatric,
            'psychiatric_dd' => $this->psychiatric_dd,
            'psychiatric_comments' => $this->psychiatric_comments,
            'general_wnl' => $this->general_wnl,
            'general_wnl_dd' => $this->general_wnl_dd,
            'general_wnl_comments' => $this->general_wnl_comments,
            'heent_wnl' => $this->heent_wnl,
            'heent_wnl_dd' => $this->heent_wnl_dd,
            'heent_wnl_comments' => $this->heent_wnl_comments,
            'skin_wnl' => $this->skin_wnl,
            'skin_wnl_dd' => $this->skin_wnl_dd,
            'skin_wnl_comments' => $this->skin_wnl_comments,
            'neck_wnl' => $this->neck_wnl,
            'neck_wnl_dd' => $this->neck_wnl_dd,
            'neck_wnl_comments' => $this->neck_wnl_comments,
            'cardio_wnl' => $this->cardio_wnl,
            'cardio_wnl_dd' => $this->cardio_wnl_dd,
            'cardio_wnl_comments' => $this->cardio_wnl_comments,
            'lungs_wnl' => $this->lungs_wnl,
            'lungs_wnl_dd' => $this->lungs_wnl_dd,
            'lungs_wnl_comments' => $this->lungs_wnl_comments,
            'abdomen_wnl' => $this->abdomen_wnl,
            'abdomen_wnl_dd' => $this->abdomen_wnl_dd,
            'abdomen_wnl_comments' => $this->abdomen_wnl_comments,
            'msk_wnl' => $this->msk_wnl,
            'msk_wnl_dd' => $this->msk_wnl_dd,
            'msk_wnl_comments' => $this->msk_wnl_comments,
            'neuro_wnl' => $this->neuro_wnl,
            'neuro_wnl_dd' => $this->neuro_wnl_dd,
            'neuro_wnl_comments' => $this->neuro_wnl_comments,
            'extremities_wnl' => $this->extremities_wnl,
            'extremities_wnl_dd' => $this->extremities_wnl_dd,
            'extremities_wnl_comments' => $this->extremities_wnl_comments,
            'billing_icd10' => $this->billing_icd10,
            'problems' => $this->problems,
            'billing_icd9' => $this->billing_icd9,
            'problem_history' => $this->problem_history,
            'assesments' => $this->assesments,
            'lab' => $this->lab,
            'lab_comms' => $this->lab_comms,
            'radiology' => $this->radiology,
            'radiology_comms' => $this->radiology_comms,
            'pt_rec' => $this->pt_rec,
            'pt_rec_comms' => $this->pt_rec_comms,
            'home_health' => $this->home_health,
            'home_health_comms' => $this->home_health_comms,
            'referrals' => $this->referrals,
            'referrals_comms' => $this->referrals_comms,
            'edu' => $this->edu,
            'edu_comms' => $this->edu_comms,
            'diet' => $this->diet,
            'diet_comms' => $this->diet_comms,
            'general_ins' => $this->general_ins,
            'general_ins_comms' => $this->general_ins_comms,
            'created_at' => $this->created_at
        ];
    }
}
