<?php

namespace App\Http\Requests\Soap;

use Illuminate\Foundation\Http\FormRequest;


class UpdateRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'clinical_note_id' => 'required|exists:clinical_notes,id',
            'hpi' => 'sometimes|string|nullable',
            'family_hx' => 'sometimes|string|nullable',
            'past_medical_hx' => 'sometimes|string|nullable',
            'social_hx' => 'sometimes|string|nullable',
            'general' => 'sometimes|boolean|nullable',
            'general_dd' => 'sometimes|string|nullable',
            'general_comments' => 'sometimes|string|nullable',
            'skin' => 'sometimes|boolean|nullable',
            'skin_dd' => 'sometimes|string|nullable',
            'skin_comments' => 'sometimes|string|nullable',
            'heent' => 'sometimes|boolean|nullable',
            'heent_dd' => 'sometimes|string|nullable',
            'heent_comments' => 'sometimes|string|nullable',
            'neck' => 'sometimes|boolean|nullable',
            'neck_dd' => 'sometimes|string|nullable',
            'neck_comments' => 'sometimes|string|nullable',
            'cardio' => 'sometimes|boolean|nullable',
            'cardio_dd' => 'sometimes|string|nullable',
            'cardio_comments' => 'sometimes|string|nullable',
            'respiratory' => 'sometimes|boolean|nullable',
            'respiratory_dd' => 'sometimes|string|nullable',
            'respiratory_comments' => 'sometimes|string|nullable',
            'gi' => 'sometimes|boolean|nullable',
            'gi_dd' => 'sometimes|string|nullable',
            'gi_comments' => 'sometimes|string|nullable',
            'urinary' => 'sometimes|boolean|nullable',
            'urinary_dd' => 'sometimes|string|nullable',
            'urinary_comments' => 'sometimes|string|nullable',
            'periph_vasc' => 'sometimes|boolean|nullable',
            'periph_vasc_dd' => 'sometimes|string|nullable',
            'periph_vasc_comments' => 'sometimes|string|nullable',
            'msk' => 'sometimes|boolean|nullable',
            'msk_dd' => 'sometimes|string|nullable',
            'msk_comments' => 'sometimes|string|nullable',
            'neuro' => 'sometimes|boolean|nullable',
            'neuro_dd' => 'sometimes|string|nullable',
            'neuro_comments' => 'sometimes|string|nullable',
            'endo' => 'sometimes|boolean|nullable',
            'endo_dd' => 'sometimes|string|nullable',
            'endo_comments' => 'sometimes|string|nullable',
            'psychiatric' => 'sometimes|boolean|nullable',
            'psychiatric_dd' => 'sometimes|string|nullable',
            'psychiatric_comments' => 'sometimes|string|nullable',
            'general_wnl' => 'sometimes|string|nullable',
            'general_wnl_dd' => 'sometimes|string|nullable',
            'general_wnl_comments' => 'sometimes|string|nullable',
            'heent_wnl' => 'sometimes|string|nullable',
            'heent_wnl_dd' => 'sometimes|string|nullable',
            'heent_wnl_comments' => 'sometimes|string|nullable',
            'skin_wnl' => 'sometimes|string|nullable',
            'skin_wnl_dd' => 'sometimes|string|nullable',
            'skin_wnl_comments' => 'sometimes|string|nullable',
            'neck_wnl' => 'sometimes|string|nullable',
            'neck_wnl_dd' => 'sometimes|string|nullable',
            'neck_wnl_comments' => 'sometimes|string|nullable',
            'cardio_wnl' => 'sometimes|string|nullable',
            'cardio_wnl_dd' => 'sometimes|string|nullable',
            'cardio_wnl_comments' => 'sometimes|string|nullable',
            'lungs_wnl' => 'sometimes|string|nullable',
            'lungs_wnl_dd' => 'sometimes|string|nullable',
            'lungs_wnl_comments' => 'sometimes|string|nullable',
            'abdomen_wnl' => 'sometimes|string|nullable',
            'abdomen_wnl_dd' => 'sometimes|string|nullable',
            'abdomen_wnl_comments' => 'sometimes|string|nullable',
            'msk_wnl' => 'sometimes|string|nullable',
            'msk_wnl_dd' => 'sometimes|string|nullable',
            'msk_wnl_comments' => 'sometimes|string|nullable',
            'neuro_wnl' => 'sometimes|string|nullable',
            'neuro_wnl_dd' => 'sometimes|string|nullable',
            'neuro_wnl_comments' => 'sometimes|string|nullable',
            'extremities_wnl' => 'sometimes|string|nullable',
            'extremities_wnl_dd' => 'sometimes|string|nullable',
            'extremities_wnl_comments' => 'sometimes|string|nullable',
            'billing_icd10' => 'sometimes|string|nullable',
            'problems' => 'sometimes|string|nullable',
            'billing_icd9' => 'sometimes|string|nullable',
            'problem_history' => 'sometimes|string|nullable',
            'assesments' => 'sometimes|string|nullable',
            'lab' => 'sometimes|string|nullable',
            'lab_comms' => 'sometimes|string|nullable',
            'radiology' => 'sometimes|string|nullable',
            'radiology_comms' => 'sometimes|string|nullable',
            'pt_rec' => 'sometimes|string|nullable',
            'pt_rec_comms' => 'sometimes|string|nullable',
            'home_health' => 'sometimes|string|nullable',
            'home_health_comms' => 'sometimes|string|nullable',
            'referrals' => 'sometimes|string|nullable',
            'referrals_comms' => 'sometimes|string|nullable',
            'edu' => 'sometimes|string|nullable',
            'edu_comms' => 'sometimes|string|nullable',
            'diet' => 'sometimes|string|nullable',
            'diet_comms' => 'sometimes|string|nullable',
            'general_ins' => 'sometimes|string|nullable',
            'general_ins_comms' => 'sometimes|string|nullable'
        ];
    }
}